name: daxle
description: A lightweight Dart utility package offering common abstractions and missing features to write safer, more expressive code.
version: 3.0.0+1
homepage: https://github.com/maranix/daxle/tree/main/packages/daxle
repository: https://github.com/maranix/daxle/tree/main/packages/daxle
issues: https://github.com/maranix/daxle/issues?q=state%3Aopen%20label%3Adaxle

topics:
  - functional
  - option
  - either
  - fp

environment:
  sdk: ^3.11.0

resolution: workspace

dependencies:
  async: ^2.13.1
  meta: ^1.18.3

dev_dependencies:
  lints: ^6.1.0
  test: ^1.31.2
