name: daxle
description: High-performance data modeling, zero-cost map querying, concurrency control, and stream transformations for Dart.
version: 5.1.0
homepage: https://github.com/maranix/daxle/tree/main/packages/daxle
repository: https://github.com/maranix/daxle/tree/main/packages/daxle
issues: https://github.com/maranix/daxle/issues?q=state%3Aopen%20label%3Adaxle

topics:
  - query-map
  - concurrency
  - stream-transform
  - codegen
  - utilities

environment:
  sdk: ^3.13.0

resolution: workspace

dependencies:
  async: ^2.13.1
  meta: ^1.19.0
  pool: ^1.5.3
  stream_transform: ^2.1.2

dev_dependencies:
  lints: ^6.1.0
  test: ^1.31.2
