name: daxle_gen
description: AST code generator and compile-time validation hook for Daxle.
version: 0.1.0+1-alpha
homepage: https://github.com/maranix/daxle/tree/main/packages/daxle_gen
repository: https://github.com/maranix/daxle/tree/main/packages/daxle_gen
issues: https://github.com/maranix/daxle/issues?q=state%3Aopen%20label%3Adaxle

topics:
  - analyzer
  - code-gen
  - generator
  - compile-time
  - comptime

environment:
  sdk: ^3.13.0

resolution: workspace

dependencies:
  analyzer: ^14.4.0
  args: ^2.7.0
  code_builder: ^4.12.0
  crypto: ^3.0.7
  dart_style: ^3.1.13
  glob: ^2.2.0
  meta: ^1.19.0
  path: ^1.9.1
  watcher: ^1.2.1

dev_dependencies:
  daxle: any
  lints: ^6.1.0
  test: ^1.31.2
